#!/usr/bin/zsh
################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
## ZSH Configuration
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

ZSH_DISABLE_COMPFIX=false

# Theme
ZSH_THEME="muse"
ZSH_THEME_VIRTUALENV_SUFFIX="]"
ZSH_THEME_VIRTUALENV_PREFIX=" ["
ZSH_THEME_SYSTEMD_PROMPT_CAPS=""

# Tmux Plugin
ZSH_TMUX_CONFIG="${HOME}/tmux/tmux.conf"
ZSH_TMUX_ITERM2=false
ZSH_TMUX_UNICODE=true
ZSH_TMUX_AUTOQUIT=false
ZSH_TMUX_DETACHED=false
ZSH_TMUX_AUTOSTART=false
ZSH_TMUX_AUTOCONNECT=false
ZSH_TMUX_AUTOREFRESH=false
ZSH_TMUX_AUTOSTART_ONCE=true

# Toggles
DISABLE_LS_COLORS=false
DISABLE_AUTO_TITLE=false
DISABLE_UNTRACKED_FILES_DIRTY=true

# Misc
HIST_STAMPS="mm/dd/yyyy"
CASE_SENSITIVE=false
ENABLE_CORRECTION=true
COMPLETION_WAITING_DOTS=true

# Plugins
plugins=(colored-man-pages copypath encode64 extract git git-lfs golang history nmap rust sudo systemd tmux)
source "${ZSH}/oh-my-zsh.sh"

# Auto Update
zstyle ':omz:update' frequency 14
zstyle ':omz:update' mode reminder

# Auto Completion
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "\e[A" up-line-or-beginning-search
bindkey "\e[B" down-line-or-beginning-search

# Compload / Compdump
autoload -U compinit
compinit -d "$ZSH_COMPDUMP"

zstyle ':compinstall' filename "${HOME}/.cache/zsh/zshcomp"

# Auto Completion Configuration
zstyle ':completion:*' completer _complete _extensions _approximate
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${HOME}/.cache/zsh/zshcomp_cache"
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name modification
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl false

zstyle ':completion:*:messages' format '%F{yellow}[%d]%f'
zstyle ':completion:*:warnings' format '%F{red}... No matches found!%f'

typeset -A ZSH_HIGHLIGHT_STYLES
source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

ZSH_HIGHLIGHT_MAXLENGTH=256
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

ZSH_HIGHLIGHT_STYLES[root]="bg=9,underline"
ZSH_HIGHLIGHT_STYLES[alias]="fg=112,bold"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=172,bold"
ZSH_HIGHLIGHT_STYLES[command]="fg=113,bold"
ZSH_HIGHLIGHT_STYLES[function]="fg=202,bold"
ZSH_HIGHLIGHT_STYLES[globbing]="fg=118,bold,underline"
ZSH_HIGHLIGHT_STYLES[global-alias]="fg=202,bold"
ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=93,bold"
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=196,bold,underline"
ZSH_HIGHLIGHT_STYLES[process-substitution]="fg=63,bold"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=220,bold"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=220,bold"
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]="fg=63,bold"
ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]="fg=63,bold"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]="fg=74,bold"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]="fg=74,bold"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]="fg=74,bold"

ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("/media")
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("/tmp/.mounts")
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("${HOME}/Volumes")
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("${XDG_RUNTIME_DIR}/mounts")

PROMPT="%n $PROMPT"

[ -d "${HOME}/Desktop" ] && rmdir "${HOME}/Desktop"

# Kitty Integration
export KITTY_SHELL_INTEGRATION="enabled"
autoload -Uz -- "/usr/lib/kitty/shell-integration/zsh/kitty-integration"
kitty-integration
unfunction kitty-integration

# From: https://github.com/jgogstad/zsh-mask
#
# With added:
# - Full path commands ^/
# - Alias "stub" commands ^\
# - Any rm/rmdir commands
# - The "history" command lol
# - Any __* commands
# - Any locally executed scripts "./script"
ZSH_HISTORY_EXCLUDE='^ |//([^/]+:[^/]+)@|KEY[=:] *([^ ]+)|TOKEN[=:] *([^ ]+)|BEARER[=:] *([^ ]+)|PASSWO?R?D?[=:] *([^ ]+)|Authorization[=:] *([^'"'"'\"]+)|-us?e?r? ([^:]+:[^:]+) |^/|^\\|^rm|^rmdir|^history|^sync-|^lxx |^lx-rn-|^smb-|^_|^\.'

# ZSH History Checker
function zshaddhistory() {
    emulate -L zsh
    unsetopt case_match
    if [[ "${1%%$'\n'}" =~ "$ZSH_HISTORY_EXCLUDE" ]]; then
        return 1
    fi
    return 0
}

function code() {
    if [ $# -eq 1 ]; then
        /usr/bin/codium "$(realpath "$1")" 2> /dev/null
    else
        /usr/bin/codium $* 2> /dev/null
    fi
}
function trash() {
    if [ $# -eq 0 ]; then
        echo "del [FILE]..."
        return 1
    fi
    for i in $*; do
        mv -i "$i" "${TRASH}/"
    done
}
function pyhttp() {
    local port="8080"
    if [ $# -ge 2 ]; then
        port="$1"
        printf 'Switching to "%s"..\n' "$2"
        cd "$2"
    elif [ $# -eq 1 ]; then
        port="$1"
    fi
    echo "IP Addresses:"
    ifconfig | grep 'inet '| awk '{print "\t"$2}' |grep -vE '127.0.0.1|172.16.172'
    python -m http.server "$port"
}
function _firewall_open() {
    sudo sh -c "nft add chain inet filter input '{ policy accept; }'; nft add chain inet filter output '{ policy accept; }'"
}
function _firewall_close() {
    sudo sh -c "nft flush table ip nat; nft flush table inet filter; nft delete table ip nat; nft delete table inet filter; nft -f /etc/nftables.conf"
}

# Golang Helpers
function go10() {
    # NOTE(dij): This needs to be function instead of an alias as we need to
    #            read $PWD when running go1.10 due to the lack of module support.
    #            If it was an alias, it would default to the $HOME directory always.
    /usr/bin/ghr firewall-all /usr/bin/env GOROOT="${HOME}/Documents/Development/GoArchive/14.15" GOPATH="$(pwd)" "${HOME}/Documents/Development/GoArchive/10.8/bin/go" $@
}

# Golang Aliases
alias wgo="nocorrect /usr/bin/ghr firewall-all /usr/bin/env GOOS=windows go"
alias go10="nocorrect go10"
alias go14="nocorrect /usr/bin/ghr firewall-all /usr/bin/env GOROOT='${HOME}/Documents/Development/GoArchive/14.15' '${HOME}/Documents/Development/GoArchive/14.15/bin/go'"
alias go16="nocorrect /usr/bin/ghr firewall-all /usr/bin/env GOROOT='${HOME}/Documents/Development/GoArchive/16.15' '${HOME}/Documents/Development/GoArchive/16.15/bin/go'"
alias go18="nocorrect /usr/bin/ghr firewall-all /usr/bin/env GOROOT='${HOME}/Documents/Development/GoArchive/18.10' '${HOME}/Documents/Development/GoArchive/18.10/bin/go'"
alias go22="nocorrect /usr/bin/ghr firewall-all /usr/bin/env GOROOT='${HOME}/Documents/Development/GoArchive/22.12' '${HOME}/Documents/Development/GoArchive/22.12/bin/go'"

# Firewall Aliases
alias go="nocorrect /usr/bin/ghr firewall-all /usr/bin/go"
alias nc="nocorrect /usr/bin/ghr firewall-all /usr/bin/nc"
alias git="/usr/bin/ghr firewall-web /usr/bin/git"
alias gpg="/usr/bin/gpg --homedir ${HOME}/.local/share/gnupg"
alias scp="/usr/bin/ghr firewall-ssh /usr/bin/scp"
alias ssh="/usr/bin/ghr firewall-ssh /usr/bin/ssh"
alias vnc="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/vncviewer"
alias yay="nocorrect /usr/bin/ghr firewall-web /usr/bin/yay"
alias curl="/usr/bin/ghr firewall-web /usr/bin/curl"
alias gvnc="/usr/bin/ghr firewall-ctl /usr/bin/gvncviewer"
alias nmap="/usr/bin/ghr firewall-all /usr/bin/nmap"
alias ping="/usr/bin/ghr firewall-icmp /usr/bin/ping"
alias wget="/usr/bin/ghr firewall-web /usr/bin/wget --hsts-file=${HOME}/.cache/wget-hsts"
alias rsync="/usr/bin/ghr firewall-ssh /usr/bin/rsync"
alias pacman="nocorrect /usr/bin/ghr firewall-web /usr/bin/pacman"
alias wython="/usr/bin/ghr firewall-web /usr/bin/python3"
alias xfreerdp="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/xfreerdp3"

# RDP Aliases
alias rdp="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/xfreerdp3 -aero +async-channels +async-update +auto-request-control -compression -decorations -drives +gestures -grab-keyboard -grab-mouse -home-drive +jpeg -menu-anims +multitouch -themes -toggle-fullscreen +video +wallpaper +window-drag /cache:bitmap:off /clipboard:use-selection:CLIPBOARD,direction-to:all,files-to:all /gdi:hw /gfx /log-level:ERROR /scale-device:100 /size:1600x900"
alias rdp_map="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/xfreerdp3 -aero +async-channels +async-update +auto-request-control -compression -decorations -drives +gestures -grab-keyboard -grab-mouse +home-drive +jpeg -menu-anims +multitouch -themes -toggle-fullscreen +video +wallpaper +window-drag /cache:bitmap:off /clipboard:use-selection:CLIPBOARD,direction-to:all,files-to:all /gdi:hw /gfx /log-level:ERROR /scale-device:100 /size:1600x900"

# Python Aliases
alias p="/usr/bin/python3"
alias python="/usr/bin/python3"

# Power Aliases
alias hib="sudo /usr/bin/systemctl hibernate"
alias sus="sudo /usr/bin/systemctl suspend"
alias bright="brightnessctl"
alias reboot="/usr/bin/systemctl reboot"
alias poweroff="/usr/bin/systemctl poweroff"

# Locker Aliases
alias chill="lockerctl -C"
alias coffee="lockerctl -z 600 -kb 300 -kl 300 -s 300"
alias caffeine="lockerctl -z 600 -kb 600 -kl 600 -s 600"
alias expresso="lockerctl -z 900 -kb 900 -kl 900 -s 900"
alias insomnia="lockerctl -kz true -kb true -kl true -ks true"

# CPU Aliases
alias power0="cpuctl -x 600Mhz -m 400Mhz -t 0 -tx 20 -tm 10 -g powersave -p power"
alias power1="cpuctl -x 800Mhz -m 400Mhz -t 0 -tx 20 -tm 10 -g powersave -p balance_power"
alias power2="cpuctl -x 1.5Ghz -m 400Mhz -t 0 -tx 40 -tm 10 -g powersave -p balance_power"
alias power3="cpuctl -x 2.5Ghz -m 400Mhz -t 1 -tx 70 -tm 10 -g performance -p balance_performance"
alias power4="cpuctl -x 3.0Ghz -m 400Mhz -t 1 -tx 85 -tm 20 -g performance -p performance"
alias power5="cpuctl -s -x 4.8Ghz -m 400Mhz -t 1 -tx 100 -tm 10 -g performance -p performance"

# LSd Aliases
alias l="/usr/bin/lsd -vFl --group-directories-first --color=auto"
alias ls="/usr/bin/lsd -vF --group-directories-first --color=auto"
alias lsa="/usr/bin/lsd -vFlA --group-directories-first --color=auto"
alias lsd="/usr/bin/lsd -vFlh --group-directories-first --color=auto"

# Screenshot Aliases
alias sel="${HOME}/.local/bin/sway/clip"
alias ssc="${HOME}/.local/bin/sway/shot copy"
alias selc="${HOME}/.local/bin/sway/clip copy"

# Go Aliases
alias gv="/usr/bin/ghr firewall-web /usr/bin/go vet ./..."
alias go-check="/usr/bin/ghr firewall-web /usr/bin/sh -c 'go mod tidy; go vet ./...; staticcheck ./...'"
alias go-update="go list -u -m -json all | go-mod-outdated -update"
alias go-outdated="go list -u -m -json all | go-mod-outdated"
alias go-check-win="/usr/bin/ghr firewall-web /usr/bin/env GOOS=windows staticcheck ./..."
alias go-tools-update="/usr/bin/ghr firewall-all '${HOME}/.local/lib/go/bin/go-global-update'"

# Rust Aliases
alias cargo="nocorrect /usr/bin/ghr firewall-web /usr/bin/cargo"
alias rust-check="/usr/bin/ghr firewall-web /usr/bin/cargo check"
alias rust-update="/usr/bin/ghr firewall-web /usr/bin/cargo install-update --all"

# Utility Aliases
alias si="/usr/bin/swayimg"
alias xx="exit"
alias cls="clear"
alias del="trash"
alias vsc="code"
alias tree="swaymsg -t get_tree"
alias wgcc="nocorrect /usr/bin/x86_64-w64-mingw32-gcc"
alias gsync="git add -A .; git commit; git push"
alias nohist="export HISTFILE=/dev/null; export HISTSIZE=0; export SAVEHIST=0"
alias weather="/usr/bin/ghr firewall-web /usr/bin/curl 'wttr.in/?0'"
alias powershell="pwsh"
alias pip_install="/usr/bin/ghr firewall-web /usr/bin/env PYTHONPYCACHEPREFIX='/var/cache/python' PIP_USER=yes /usr/bin/python3 -X pycache_prefix='/var/cache/python' -OO /usr/bin/pip install --break-system-packages"

# Fixup Aliases
alias find="noglob /usr/bin/find"
alias hydra="nocorrect hydra"
alias convert="nocorrect convert"

# Arguments Aliases
alias jq="/usr/bin/jq -C"
alias rm="/usr/bin/rm -I"
alias cat="/usr/bin/bat --paging=never"
alias sat="/usr/bin/cat"
alias clip="/usr/bin/wl-copy --trim-newline"
alias diff="/usr/bin/diff --color=auto"
alias less="/usr/bin/less -iR"
alias nano="/usr/bin/nano -SLlwxiE --tabsize=4"

# Script Aliases
alias nts="/usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/ntstatus.py'"
alias fih="/usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/image_hash.py'"
alias fls="/usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/linesort.py'"
alias fmov="/usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/file_move.py'"
alias fren="/usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/file_rename.py'"
alias fnorm="noglob nocorrect /usr/bin/python3 -X pycache_prefix=/var/cache/python -OO '${HOME}/.local/scripts/file_normalize.py'"

source "${HOME}/.local/lib/zshrc.sh"
source "${HOME}/.local/share/colors.sh"

shuf -n1 "${HOME}/.config/quotes.db" | cowsay -W 75 -f small | lolcat --random --horizontal-frequency 0.2 --vertical-frequency 1.25
