#!/usr/bin/zsh
################################
### iDigitalFlame  2016-2024 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
## ZSH Configuration
#
# Copyright (C) 2016 - 2024 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# OhMyZsh Configuration Options
ZSH_THEME="muse"
CASE_SENSITIVE=false
ENABLE_CORRECTION=true
DISABLE_LS_COLORS=false
HIST_STAMPS="mm/dd/yyyy"
DISABLE_AUTO_TITLE=false
ZSH_DISABLE_COMPFIX=false
COMPLETION_WAITING_DOTS=true
DISABLE_UNTRACKED_FILES_DIRTY=true

[ ! -d "$AURDEST" ] && mkdir -p "$AURDEST"
[ ! -d "$SRCDEST" ] && mkdir -p "$SRCDEST"
[ ! -d "$BUILDDIR" ] && mkdir -p "$BUILDDIR"
[ ! -d "${HOME}/.cache/zsh" ] && mkdir -p "${HOME}/.cache/zsh"
[ ! -d "${HOME}/Pictures/Screenshots" ] && mkdir -p "${HOME}/Pictures/Screenshots"

if [ ! -d "/tmp/.usercache/${USER}/trash" ]; then
    mkdir -p "/tmp/.usercache/${USER}/trash"
    rm -f "${HOME}/.local/share/Trash"
    ln -s "/tmp/.usercache/${USER}/trash" "${HOME}/.local/share/Trash"
fi

[ -d "${HOME}/Desktop" ] && rmdir "${HOME}/Desktop"

# OhMyZsh Plugins
plugins=(archlinux git screen systemd sudo)
source "${ZSH}/oh-my-zsh.sh"

zstyle ':omz:update' frequency 14
zstyle ':omz:update' mode reminder

# ZSH Auto Completion
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "\e[A" up-line-or-beginning-search
bindkey "\e[B" down-line-or-beginning-search

autoload -U compinit
compinit -d "$ZSH_COMPDUMP"

zstyle ':compinstall' filename "${HOME}/.cache/zsh/zshcomp"

# Auto Completion Options
zstyle ':completion:*' completer _complete _extensions _approximate
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${HOME}/.cache/zsh/zshcomp_cache"
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name modification
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl false

zstyle ':completion:*:messages' format '%F{yellow}[%d]%f'
zstyle ':completion:*:warnings' format '%F{red}... No matches found!%f'

typeset -A ZSH_HIGHLIGHT_STYLES
source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

ZSH_HIGHLIGHT_MAXLENGTH=256
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

ZSH_HIGHLIGHT_STYLES[alias]='fg=112,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=113,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=172,bold'
ZSH_HIGHLIGHT_STYLES[root]='bg=9,underline'
ZSH_HIGHLIGHT_STYLES[function]='fg=202,bold'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=202,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=93,bold'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=118,bold,underline'
ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=63,bold'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=220,bold'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=220,bold'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=196,bold,underline'
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=63,bold'
ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]='fg=63,bold'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=74,bold'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=74,bold'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=74,bold'

ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("/media")
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("/tmp/.mounts")
ZSH_HIGHLIGHT_DIRS_BLACKLIST+=("${HOME}/Volumes")

PROMPT="%n $PROMPT"

# Integrate with Kitty
export KITTY_SHELL_INTEGRATION="enabled"
autoload -Uz -- "/usr/lib/kitty/shell-integration/zsh/kitty-integration"
kitty-integration
unfunction kitty-integration

cess() {
    if [ $# -lt 1 ]; then
        echo "cess <file1> <fileN..>" 1>&2
        return
    fi
    /usr/bin/bat --paging=never $@ | less
}
firewall_open() {
    /usr/bin/cat<<EOF | sudo -i --
nft add chain inet filter input '{ policy accept; }'
nft add chain inet filter output '{ policy accept; }'
EOF
}
firewall_close() {
    /usr/bin/cat<<EOF | sudo -i --
nft flush table ip nat
nft flush table inet filter
nft delete table ip nat
nft delete table inet filter
nft -f /etc/nftables.conf
EOF
}

# TODO(dij): Use gotip or another method instead? Need to see if it can handle
#            older go toolchains.
# Golang Version helper functions
go1.10() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.10.8\"; export GOPATH=\"$(pwd)\"; \"${HOME}/Documents/Development/GoArchive/go1.10.8/bin/go\" $_args"
}
go1.11() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.11.13\"; \"${HOME}/Documents/Development/GoArchive/go1.11.13/bin/go\" $_args"
}
go1.12() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.12.17\"; \"${HOME}/Documents/Development/GoArchive/go1.12.17/bin/go\" $_args"
}
go1.13() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.13.15\"; \"${HOME}/Documents/Development/GoArchive/go1.13.15/bin/go\" $_args"
}
go1.14() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.14.15\"; \"${HOME}/Documents/Development/GoArchive/go1.14.15/bin/go\" $_args"
}
go1.15() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.15.15\"; \"${HOME}/Documents/Development/GoArchive/go1.15.15/bin/go\" $_args"
}
go1.16() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.16.15\"; \"${HOME}/Documents/Development/GoArchive/go1.16.15/bin/go\" $_args"
}
go1.17() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.17.13\"; \"${HOME}/Documents/Development/GoArchive/go1.17.13/bin/go\" $_args"
}
go1.18() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.18.10/\"; \"${HOME}/Documents/Development/GoArchive/go1.18.10/bin/go\" $_args"
}
go1.19() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.19.5\"; \"${HOME}/Documents/Development/GoArchive/go1.19.5/bin/go\" $_args"
}
go1.20() {
    _args=$@
    ghr firewall-web /usr/bin/sh -c "export GOROOT=\"${HOME}/Documents/Development/GoArchive/go1.20.6\"; \"${HOME}/Documents/Development/GoArchive/go1.20.6/bin/go\" $_args"
}

# Firewall Aliases
alias nc="/usr/bin/ghr firewall-all /usr/bin/nc"
alias yay="/usr/bin/ghr firewall-web /usr/bin/yay"
alias ssh="/usr/bin/ghr firewall-ssh /usr/bin/ssh"
alias scp="/usr/bin/ghr firewall-ssh /usr/bin/scp"
alias git="/usr/bin/ghr firewall-web /usr/bin/git"
alias nmap="/usr/bin/ghr firewall-all /usr/bin/nmap"
alias curl="/usr/bin/ghr firewall-web /usr/bin/curl"
alias ping="/usr/bin/ghr firewall-icmp /usr/bin/ping"
alias rsync="/usr/bin/ghr firewall-ssh /usr/bin/rsync"
alias pacman="/usr/bin/ghr firewall-web /usr/bin/pacman"
alias vnc="/usr/bin/ghr firewall-ctl /usr/bin/gvncviewer"
alias wython="/usr/bin/ghr firewall-web /usr/bin/python3"
alias go="nocorrect /usr/bin/ghr firewall-web /usr/bin/go"
alias gpg="/usr/bin/gpg --homedir ${HOME}/.local/share/gnupg"
alias gpg2="/usr/bin/gpg2 --homedir ${HOME}/.local/share/gnupg"
alias quote="/usr/bin/ghr firewall-web ${HOME}/.local/bin/motivate -n"
alias xfreerdp="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/wlfreerdp"
alias vncviewer="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/vncviewer"
alias wgo="nocorrect env GOOS=windows /usr/bin/ghr firewall-web /usr/bin/go"
alias wget="/usr/bin/ghr firewall-web /usr/bin/wget --hsts-file=${HOME}/.cache/wget-hsts"
alias rdp="nocorrect /usr/bin/ghr firewall-ctl /usr/bin/wlfreerdp -aero +async-channels -compression -decorations -grab-keyboard -grab-mouse +home-drive -menu-anims +multitouch +clipboard -themes /size:1920x1035"

# Python Aliases
alias p="/usr/bin/python3"
alias python="/usr/bin/python3"

# Power Aliases
alias bright="brightnessctl"
alias reboot="systemctl reboot"
alias poweroff="systemctl poweroff"
alias sus="sudo /usr/bin/systemctl suspend"
alias hib="sudo /usr/bin/systemctl hibernate"

# Locker Aliases
alias coffee="lockerctl -z 600 -kb 300 -kl 300 -s 300"
alias caffeine="lockerctl -z 600 -kb 600 -kl 600 -s 600"
alias expresso="lockerctl -z 900 -kb 900 -kl 900 -s 900"
alias insomnia="lockerctl -kz true -kb true -kl true -ks true"
alias chill="lockerctl -kz false -kb false -kl false -ks false -kd false"

# CPU Aliases
alias power0="cpuctl -x 600Mhz -m 400Mhz -t 0 -tx 20 -tm 10 -g powersave -p power"
alias power1="cpuctl -x 800Mhz -m 400Mhz -t 0 -tx 20 -tm 10 -g powersave -p balance_power"
alias power2="cpuctl -x 1.5Ghz -m 400Mhz -t 0 -tx 40 -tm 10 -g powersave -p balance_power"
alias power3="cpuctl -x 2.5Ghz -m 400Mhz -t 1 -tx 70 -tm 10 -g performance -p balance_performance"
alias power4="cpuctl -x 3.0Ghz -m 400Mhz -t 1 -tx 85 -tm 20 -g performance -p performance"
alias power5="cpuctl -x 4.0Ghz -m 400Mhz -t 1 -tx 100 -tm 10 -g performance -p performance"

# LSd Aliases
alias l="/usr/bin/lsd -vFl --group-directories-first --color=auto"
alias ls="/usr/bin/lsd -vF --group-directories-first --color=auto"
alias lsd="/usr/bin/lsd -vFlh --group-directories-first --color=auto"
alias lsa="/usr/bin/lsd -vFlA --group-directories-first --color=auto"

# Screenshot Aliases
alias sel="${HOME}/.local/bin/sway/clip"
alias selc="/usr/bin/grimshot --notify copy area"
alias ssc="/usr/bin/grimshot --notify copy output"

# Go Aliases
alias gmo="go list -u -m -json all | go-mod-outdated"
alias gv="/usr/bin/ghr firewall-web /usr/bin/go vet ./..."
alias gmou="go list -u -m -json all | go-mod-outdated -update"
alias gsc-win="/usr/bin/ghr firewall-web /usr/bin/env GOOS=windows staticcheck ./..."
alias gsc="/usr/bin/ghr firewall-web ${HOME}/.local/lib/go/bin/staticcheckstaticcheck ./..."
alias gov="/usr/bin/ghr firewall-web /usr/bin/sh -c 'go mod tidy; go vet ./...; staticcheck ./...; fieldalignment ./...'"

# Utility Aliases
alias xx="exit"
alias cls="clear"
alias powershell="pwsh"
alias sat="/usr/bin/cat"
alias pat="/usr/bin/bat"
alias find="noglob find"
alias rm="/usr/bin/rm -I"
alias jq="/usr/bin/jq -C"
alias hydra="nocorrect hydra"
alias less="/usr/bin/less -iR"
alias tree="swaymsg -t get_tree"
alias convert="nocorrect convert"
alias cat="/usr/bin/bat --paging=never"
alias diff="/usr/bin/diff --color=auto"
alias clip="/usr/bin/wl-copy --trim-newline"
alias nano="/usr/bin/nano -SLlwxiE --tabsize=4"
alias gsync="git add -A .; git commit; git push"
alias wgcc="nocorrect /usr/bin/x86_64-w64-mingw32-gcc"
alias weather="/usr/bin/ghr firewall-web /usr/bin/curl 'wttr.in/?0'"
alias pip_install="/usr/bin/ghr firewall-web /usr/bin/env PIP_USER=yes /usr/bin/pip install --break-system-packages"

# Script Aliases
alias pmov="/usr/bin/python3 ${HOME}/Projects/Scripts/Python/move.py"
alias pfx2pem="/usr/bin/dash ${HOME}/Projects/Scripts/Shell/pfx2pem.sh"
alias nts="/usr/bin/python3 ${HOME}/Projects/Scripts/Python/ntstatus.py"
alias dirdiff="/usr/bin/python3 ${HOME}/Projects/Scripts/Python/dirdiff.py"

# Application Aliases
alias vsc="/usr/bin/vscodium --enable-features=WaylandWindowDecorations --ozone-platform-hint=wayland --unity-launch"
alias code="/usr/bin/vscodium --enable-features=WaylandWindowDecorations --ozone-platform-hint=wayland --unity-launch"

source "${HOME}/.local/lib/zshrc.sh"
source "${HOME}/.local/share/colors.sh"

motivate | cowsay -W 75 -f small | lolcat --random --horizontal-frequency 0.2 --vertical-frequency 1.25
