#!/usr/bin/bash
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Auto Monitor
# Automatically chooses and sets up the extended display

MONITOR="eDP1"
MONITORS=$(xrandr | grep -E ' connected' | awk '{print $1}' | grep -v $MONITOR)
if [ ! -z "$MONITORS" ]; then
  MONITOR_POS=0
  MONITOR_NUM=0
  MONITOR_MODE=0
  COMMAND="/usr/bin/xrandr"
  if [[ $# -eq 1 ]] && [[ "$1" == "-r" ]]; then
    MONITOR_MODE=1
  fi
  if [[ $# -eq 1 ]] && [[ "$1" == "-s" ]]; then
    MONITOR_MODE=2
  fi
  if [ $MONITOR_MODE -eq 1 ]; then
    for selected_monitor in $MONITORS; do
      COMMAND="$COMMAND --output $selected_monitor --mode 1920x1080 --pos $((1920*$MONITOR_NUM))x0 --rotate normal"
      if [ $MONITOR_MODE -ne 2 ]; then 
        MONITOR_NUM=$(($MONITOR_NUM + 1))
      fi
    done
    if [$MONITOR_MODE -eq 2 ]; then
      $MONITOR_NUM=1
    fi
    COMMAND="$COMMAND --output $MONITOR --primary --mode 1920x1080 --pos $((1920*$MONITOR_NUM))x0 --rotate normal"
  else
    COMMAND="$COMMAND --output $MONITOR --primary --mode 1920x1080 --pos $((1920*$MONITOR_NUM))x0 --rotate normal"
    MONITOR_NUM=1
    for selected_monitor in $MONITORS; do
      COMMAND="$COMMAND --output $selected_monitor --mode 1920x1080 --pos $((1920*$MONITOR_NUM))x0 --rotate normal"
      if [ $MONITOR_MODE -ne 2 ]; then 
        MONITOR_NUM=$(($MONITOR_NUM + 1))
      fi
    done
  fi
  eval "$COMMAND"
  next-bg
fi
# <<EOF>> #
