#!/usr/bin/python3
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Easy Motovation
# Start your day right!

import sys

from random import choices
from os.path import realpath

MESSAGES = [
 'The only thing stopping you from sucess, is yourself!',
 '615 SWOLE IS THE GOAL, SIZE IS THE PRIZE, IT\'S GAINS O\'CLOCK MOTHERFUCKER LETS GO!!',
 'Fuck all of your excuses! Sit the fuck down and do your work!',
 'Do something today that your future self will thank you for!',
 'Never wait for things to happen, make them happen for yourself, through hard graft and not giving up!',
 'Don\'t chase people, be an example, work hard and be yourself, the people who belong will come and find you, just do your thing!',
 'If you want it, work for it. It\'s that simple.',
 'On the other side of fear, lies freedom.',
 'Sucess is the result of continuous and persistant effort.',
 'If you get tired, learn to rest, not to quit.',
 'If you don\'t sacrifice for what you want, what you want becomes the sacrifice.',
 'You have survived every single bad day so far.',
 'Do what you love, love what you do, its time to start living!',
 'Be ambitious. Keep your priorities straight, your mind right and your head up.',
 'This is your life, it hurts a whole fucking lot sometimes, but its your life, and its beautiful.',
 'It is possible to commit no mistakes and still lose. That is not a weakness, that is life.',
 'Be the person you needed when you were younger.',
 'No one will thank you for working yourself to death.',
 'A ship in harbor is safe, but that is not what ships are built for.',
 'Never make someone a priority when all you are to them is an option.',
 'Success isn\'t owned, it\'s leased, and the rent is due everyday.',
 'Problems end up in the the hospital, prison or the morgue. Everything else is just an inconvenience.',
 'Don\'t Panic.',
 'Always strive to be a better person than those who have wronged you.',
 'Life begins outside of your comfort zone.',
 'Be the Light in the Darkness.',
 'I will find my way, or make it myself.',
 '"I\'m Bored" is a useless thing to say, you live in a great, big vast world that you\'ve seen NONE percent of! The fact that you\'re alive right not is amazing, so you don\'t get to say "I\'m Bored"!',
 'The man who thinks he can and the man who thinks he can\'t are both right',
 'We don\'t always control what happens to us. But we always control how we interpet what happens to us, as well as how we respond.',
 'Hard work many not always result in success, but it will never result in regret',
 'No matter how slow you go, you are still lapping everybody on the couch',
 'There\'s no magic pill. No special shake. No secret diet. Just get off your ass.',
 'Do the fucking work. Don\'t be lazy',
 'Stop fucking waiting. It\'s time',
 'Rely on yourself. The universe doesn\'t give a fuck',
 'Be fucking practical. Success is not a theory',
 'Be productive early. Don\'t fuck around all day.',
 'Don\'t be a fucking baby. Life\'s hard. Get on with it',
 'Don\'t hang out with fuckwits',
 'Don\'t wase time on shit you can\'t control',
 'Stop bullshitting. It\'s fucking embarrassing',
 'Stop being a fucking people-pleaser. It\'s sad',
 'Stop putting toxic shit in your body. It\'s fucking stupid',
 'Stop doing the same fucking thing and hoping shit will change',
 'Don\'t cling to a mistake just because you spent a lot of time making it.',
 'Don\'t decrease the goal. Increase the effort.',
 'I don\'t stop when I\'m tired, I stop when I\'m done',
 'You\'ll have bad times but it\'ll always wake you up to the good stuff you weren\'t paying attention to',
 'If you can\'t fly, then run. If you can\'t run, then walk. If you can\'t walk, then crawl. But whatever you do, you have to keep moving forward.',
 'The best revenge is massive success.',
 'If I quit now, I will soon be back where I started and when I started, I was desperately wishing to be where I am now.',
 'A river cuts through rock, not because of its power, but because of its persistence.',
 'If you only focus on the problem, You might miss the easy solution.',
 'Fall seven times, stand up eight.',
 'It dosen\'t matter how many resources you have... If you don\'t know how to use them, it will never be enough.',
 'Stop overthinking and quit making up problems that don\'t exist.',
 'Just because you haven\'t got it all figured out, dosen\'t mean you never will. Some day you may even look back and wonder why you were ever worried.',
 'Direction is so much more important than speed. Many are going nowhere fast.',
 'Just because you took longer than others, dosen\'t mean you failed. Remember that.',
 '"Sexiest" is great. But what excited me most was hearing I was alive. - The Rock on People Magazine naming him "Sexiest Man Alive".',
 'Keep the ones that heard you when you neversaid a word',
 'Don\'t cling to a mistake just because you spend a lot of time making it.',
 'You not wanting me, was the beginning of me wanting myself. Thank you.',
 'Remember that just because you hit bottom dosen\'t mean you have to stay there.',
 'Almost every sucessful person begins with two beliefs: the future can be better than the present, and I have the power to make it so.',
 'Don\'t give up, you\'ve still got a couple of motherfuckers to prove wrong.',
 'Good decisions come from experience. But experience comes from bad decisions. This is life so, never regret. Learn from mistakes and go ahead.',
 'It feels good to be lost in the right direction.',
 'For what it\'s worth: It\'s never too late to be whoever you want to be. I hope you live a life you\'re proud of and if you find that you\'re not, I hope you have the strength to start over.',
 'Just because te past didn\'t turn out like you wanted it to, dosen\'t mean your future can\'t be better than you ever imagined',
 'Read 500 pages every day. That\'s how knowledge works. It builds up, like compound interest. All of you can do it, but I guarantee not many of you will do it.',
 'No matter how you feel, Get up, Dress up, Show up and NEVER GIVE UP.',
 'Never be afraid to try something new. Remember, amateurs built the ark. Professionals built the Titanic.',
 'I\'d rather look stupid doing something new than feeling stupid for not trying it.',
 'Sometimes you just have to chuck it in the fuck it bucket and more on.',
 'Yesterday You said Tomorrow.',
 'However difficult life may seem, there is always something you can do and succed at. It matters that you don\'t just give up.',
 'Sometimes it takes 10 years to get that 1 year that will change your life.',
 'Failure and success lve next door to each other and they have no numbers at the door. You just knock.',
 'Start now. Start where you are. Start with fear. Start with pain. Start with doubt. Start with hands shaking. Start with voice trembling but start. Start and don\'t stop. Start where you are , with what you have. Just... start',
 'You wake up every morning to fight the same deamons that left you so tired the night before, and that, my love, is bravery.',
 'Accept your past without regret, handle your present with confidence, and face your future without fear.',
 'Remember when you wanted what you currently have.',
 'If you look for the light, you can often find it. But if you look for the dark, that is all you will ever see.',
 'Worrying is like praying for something that you don\'t want to happen.',
 'If you\'re having a bad day, Take a deep breath. Remember.. It\'s just a bad day, not a bad life.',
 'Every day may not be good, but there\'s something good in every day.',
 'Don\'t every let somebody tell you that you can\'t do something. You got a dream, you gotta protect it. People can\'t do something themselves, they wanna tell you you can\'t do it. If you want something, go get it. Period.',
 'The worst days will end. The best days will end. Remember that.',
 'Do not pray for an easy life, pray for the strength to endure a difficult one.',
 'Make yourself a priority once in a while. It\'s not selfish. It\'s nescessary.',
 'Pretending to not be afraid is as good as actually not being afraid.',
 'If you have been brutally broken but still have the courage to be gentle to other living beings, Then you\'re a badass with a heart of an angel.',
 'Your speed dosen\'t matter, foward is forward.',
 'Never wish them pain. That\'s not who you are. If they caused you pain, they must have pain inside. Wish them healing.',
 'If you haven\'t the strength to impose your own terms upon life, you must accept the terms it offers you.',
 'After all these years I\'ve started to feel better about myself, and so can you.',
 'Start with what you have till you get what you want.',
 'One day you\'ll wake up and there won\'t be any more time to do the things you\'ve always wanted. Do it now.',
 'I see all the efforts you make and I am proud.',
 'Conquer the unknown.',
 'It\'s easy to do permanent damage, when y\'re temporarily upset.',
 'The lesson is that you can still make mistakes and be forgiven.',
 'Life is under no obligation to give us what we expect.',
 'I???m not afraid of death, but I???m in no hurry to die. I have so much I want to do first.',
 'Life turns on a dime, don\'t get too comfortable.',
 'Live the life YOU wanna live, not the life other people want you to live.',
 'Don\'t make your career be your life. Let it be your passion, but don\'t let it become your identity. You are so much more valuable that that.',
 'Show up, finish your projects, then brag about it. No one wants to read the first third of a book.',
 'You dont have to burn yourself to warm others',
 'The hardest battles are fought in the mind',
 'You can have results or excuses, but not both.',
 'If you want people to like you, like yourself first.',
 'I have no special talents, I am only passionately curious.',
 'Life is unethical, if you\'re trying to be ethical, you\'re playing with a disibility.',
 'Be who you are and say what you feel, because those who mind don\'t matter and those who matter don\'t mind.',
 'Ever tried. Ever failed. No matter, Try again. Fail again. Fail better.',
 'The universe isn\'t out to get you. The universe isn\'t trying to help you. The universe doesn\'t give a shit.',
 'Get comfortable, being uncomfortable.',
 'Never engage with ethical hackers. Because ethical is just an adjective.',
]


if __name__ == '__main__':
    if len(sys.argv) > 1:
        quote = str(sys.argv[1]).replace('\'', '\\\'')
        if quote not in MESSAGES:
            handle = open(realpath(__file__), 'r+')
            data = handle.read()
            handle.seek(0)
            data = data.replace(',\n]', ',\n \'%s\',\n]' % quote)
            handle.write(data)
            handle.truncate()
            handle.flush()
            handle.close()
            del data
            del handle
        del quote
    else:
        print(choices(MESSAGES)[0])
    sys.exit(0)

# EOF