#!/usr/bin/sh
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## OPerms Reset
# Resets permissions for files.
# Updated 06/05/2018

chmod -R 550 "$HOME/.dotfiles"
chown -R iDigitalFlame:iDigitalFlame "$HOME/.dotfiles"
find "$HOME/.dotfiles" -type f -exec chmod 440 {} \;
chmod -R 770 "$HOME/.dotfiles/.git"
chmod -R 550 "$HOME/.dotfiles/.bin"
chmod 550 "$HOME/.dotfiles/.zshrc"

# EOF