#!/usr/bin/python3

import sys
import json
import requests

s = requests.session()
s.headers['Content-Type'] = 'application/x-www-form-urlencoded'

r = s.post('http://www.forismatic.com/api/1.0/', data='method=getQuote&lang=en&format=json')

if r.status_code == 200:
    q = json.loads(r.content.decode('utf-8').replace('\\',''))
    print(q['quoteText'])
    print('- %s' % q['quoteAuthor'])
    del q
    del r
    del s
    sys.exit(0)
del r
del s
sys.exit(1)
