#!/usr/bin/bash
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Dev Del
# Hotfix to remove an USB device to a running Hydra VM.
# Updated 06/05/2018

if [ $# -ne 2 ]; then
  printf "$0 <vm_id> <id>\n"
  exit 1
fi

vmid=$1
usbid=$2
sudo sh -c "chown kvm -R /dev/bus/usb/; printf \"device_del usb$usbid\n\" | netcat -U /var/run/hydra/$vmid.mon"
exit 0

# EOF