#!/usr/bin/sh

if [ $# -ne 4 ]; then
  printf "$0 <vm_id> <id> <vendorid> <productid>\n"
  exit 1
fi

vmid=$1
usbid=$2
vendor=$3
product=$4
sudo chown kvm -R /dev/bus/usb/
sudo sh -c "printf \"device_add usb-host,vendorid=0x$vendor,productid=0x$product,id=usb$usbid\n\" | netcat -U /var/run/hydra/$vmid.mon"
exit 0