#!/usr/bin/sh
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Locker
# Creates the lockscreen
# Updated 06/09/2018

/usr/bin/i3lock -n \
--composite \
--show-failed-attempts \
--force-clock \
--ignore-empty-password \
--bar-indicator \
--bar-color=00000000 \
--bar-periodic-step=15 \
--bar-step=10 \
--bar-base-width=15 \
--bar-orientation=horizontal \
--bar-direction=2 \
--linecolor=#$(openssl rand -hex 3)E6 \
--separatorcolor=#$(openssl rand -hex 3)E6 \
--datecolor=000000FF \
--timecolor=000000FF \
--keyhlcolor=#$(openssl rand -hex 3)E6 \
--bshlcolor=#$(openssl rand -hex 3)E6 \
--ringvercolor=E6DB74E6 \
--ringwrongcolor=FF5555E6 \
--time-align=1 \
--date-align=1 \
--timepos="x+60:y+90" \
--datestr="%A %B %d" \
--timestr="%H:%M" \
--timesize=26 \
--datesize=18 \
--screen=eDP1 \
--wrongtext="" \
--noinputt="" \
--veriftext="" \
--pointer=default \
--color=000000 \
--image="/home/iDigitalFlame/.config/lockscreen.png" \
--tiling \
--modsize=1

# EOF