#!/usr/bin/sh
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Power
# Power menu using Rofi
# Updated 06/05/2018

case $(printf "Lock\nLogoff\nHibernate\nReboot\nPoweroff" | rofi -dmenu -lines 5 -padding 18 -width 50 -location 2 -yoffset 100) in
    "Lock")
    /opt/spaceport/bin/powerctl lock -f
    ;;
    "Hibernate")
    /usr/bin/systemctl hibernate
    ;;
    "Logoff")
    /usr/bin/i3-msg exit
    ;;
    "Reboot")
    /usr/bin/reboot
    ;;
    "Poweroff")
    /usr/bin/poweroff
    ;;
esac
exit 0

# EOF