#!/usr/bin/sh
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Select
# Window workspace selector usign Rofi
# Updated 06/05/2018

WS=$(printf "Workspace #1\nWorkspace #2\nWorkspace #3\nWorkspace #4\nWorkspace #5\nWorkspace #6\nWorkspace #7\nWorkspace #8\nWorkspace #9\nWorkspace #10" | rofi -dmenu -padding 18 -width 50 -location 2 -yoffset 100)
if [ ! -z "$WS" ]; then
    WS_NUM=$(echo $WS | sed 's/Workspace #//g')
    i3-msg "move container to workspace $WS_NUM" > /dev/null
    if [ $# -eq 1 ]; then
        i3-msg "workspace $WS_NUM" > /dev/null
    fi
fi
exit 0

# EOF