#!/usr/bin/sh
################################
###### iDigitalFlame 2018 ######
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
################################
## Select Workspace
# iDigitalFlame 2018

WS=$(awk 'BEGIN {for(i=1;i<=20;++i) print "Workspace #"i}' | rofi -dmenu -p 'Move to Workspace' -padding 18 -width 50 -location 2 -yoffset 100)
if [ ! -z "$WS" ]; then
    WS_NUM=$(echo $WS | sed 's/Workspace #//g')
    i3-msg "move container to workspace $WS_NUM" > /dev/null
    if [ $# -eq 1 ]; then
        i3-msg "workspace $WS_NUM" > /dev/null
    fi
fi
exit 0

# EOF